### ISSUE TITLE
Browser pod immediately terminated after start

### ISSUE THREAD

**Issue by random1st** [aerokube/charts#101]
No idea what's wrong. Browser pod consists of 3 containers but with disabled video the same situation

**Comment by random1st** [comment]
It is not related to Moon, just problem in initialization of browser

**Comment by gfrntz** [comment]
@random1st could you provide more information about your solution? Thanks.

**Comment by gfrntz** [comment]
Solution: fixed by changing the AWS ELB timeout.

**Comment by vania-pooh** [comment]
@gfrntz yes, Moon automatically deletes browser pods when you disconnect. So if ELB closes connection because of timeout, pod is deleted.
