### ISSUE TITLE
Posiblility to change namespace

### ISSUE THREAD

**Issue by rebla** [aerokube/charts#109]
Currently, the namespace comes from {{ .Release.name }}

Could you add a posibility to override from values.yml?
I'm reaching the limitation of pods given from max-moon-sessions when used as a dependency chart.

**Comment by vania-pooh** [comment]
@rebla don't get the issue. In Helm namespace is provided in `helm upgrade --install` command.

**Comment by rebla** [comment]
I'm using moon as a dependency, so all pods coming from moon are installed on the same namespace as the parent helm chart reaching the hard limit of 6 pods without running any browser. It could be useful to install it directly on its own namespace or modify the script that makes the calculation for `max-moon-sessions`

**Comment by vania-pooh** [comment]
@rebla in fact you can add the following label to pods with other software to prevent Moon from considering them as browser pods: `app = moon`. This is described [here](https://aerokube.com/moon/latest/#license-how-it-works).

**Comment by rebla** [comment]
Tried and working. Thanks!
