### ISSUE TITLE
Custom Ingress definition support

### ISSUE THREAD

**Issue by achandwaniya-srcit** [aerokube/charts#119]
In perious version of Moon (V1) [charts/moon/values.yaml](https://github.com/aerokube/charts/blob/2.0.0/moon/values.yaml), we are able to customise Ingress (enable/disable), able to modify Ingress Class. But in Latest version (V2) [charts/moon2/values.yaml](https://github.com/aerokube/charts/blob/2.0.0/moon2/values.yaml) there is no option to modify Ingress.

We want to use AWS ALB as a IngressClass and want to customise ingress annotations, so is there any way by which we can customise Ingress with V2 as we did in V1?

**Comment by vania-pooh** [comment]
@achandwaniya-srcit yes, sounds reasonable. We'll consider adding a field for custom Ingress definition to values.

**Comment by vania-pooh** [comment]
Fixed in #121.

**Comment by vania-pooh** [comment]
Release as chart 2.1.0.
