### ISSUE TITLE
Custom annotations + ingressClassName on Moon V2 ingress

### ISSUE THREAD

**Issue by Firaenix** [aerokube/charts#120]
As the name suggests, the current Moon 2 helm chart doesn't allow the setting of custom ingressClassName or annotations.
I'd like to add a specific cert manager issuer annotation + some oauth2 redirect annotations.

**Comment by Firaenix** [comment]
On top of this, setting my own TLS secret names would also be appreciated so I can support my cert-manager workflow.

**Comment by vania-pooh** [comment]
Let's consider this a duplicate of #119 . Will implement soon. We decided to create a minimalist chart first and only added features on demand there.
