### ISSUE TITLE
Add option to set annotation on the aerokube provided serviceaccount (Moon2)

### ISSUE THREAD

**Issue by dani-CO-CN** [aerokube/charts#126]
I am using moon with role-based access to S3 on AWS. In moon1 there was an option to set annotations on the service account provided by the moon helm chart, i really like that the helm chart in v2 allows to specify a different service-account. But for upgrading from moon to moon2, i would now need to create another service account to set the annotation. Could we just add the code from moon1 helm chart? 

```yaml
  {{- if and .Values.moon.serviceaccount .Values.moon.serviceaccount.annotations }}
  annotations:
  {{- range $key, $value := .Values.moon.serviceaccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
```

**Comment by vania-pooh** [comment]
@dani-CO-CN please send a PR.

**Comment by aandryashin** [comment]
Fixed in https://github.com/aerokube/charts/pull/127

**Comment by vania-pooh** [comment]
Released in chart version https://github.com/aerokube/charts/releases/tag/2.1.3.
