### ISSUE TITLE
Use dedicated service account for moon-browser pod

### ISSUE THREAD

**Issue by dani-CO-CN** [aerokube/charts#129]
i think the helm chart should create an explicit serviceaccount for the moon browser pods and not use the default serviceaccount, since this grants the browser pod all permissions of the default serviceaccount. In a dedicated namespace and we could use the default serviceaccount (But if multiple apps share a namespace and pods don't have an explicit SA they will use the default SA with roles or cluster roles the SA might have higher privileges). Even in a dedicated namespace the helm chart has no option to set an annotation for the default serviceaccount to allow the upload to s3.
So my proposed change would be:
1. create a dedicated SA for moon browser pods instead of default
2. make the creation of the SA optional (so the SA does not get created if a SA is specified via helm: configs.default.serviceAccountName: someother-serviceaccount)
3. allow setting annotations on the dedicated SA, so i can grant the SA the aws-role

**Comment by aandryashin** [comment]
Hello! Ok, I can automate service account creation using a helm chart, but
as you know moon can use multiple namespaces for different teams, and there
should be different service accounts with their own annotations, so there
should be multiple service account creation. What do you think?

вс, 3 апр. 2022 г. в 13:32, dani-CO-CN ***@***.***>:

**Comment by aandryashin** [comment]
Fixed in: https://github.com/aerokube/charts/pull/130
