### ISSUE TITLE
custom location

### ISSUE THREAD

**Issue by podguzovvasily** [aerokube/charts#206]
Dear developers, Is it possible to deploy a moon in another location like moon.example.com/moon/? This is necessary because the namespace already has an application that refers to the root location. Thank you!

**Comment by vania-pooh** [comment]
@podguzovvasily our default Ingress object deploys everything under `/`. But you can use [customIngress](https://github.com/aerokube/charts/blob/master/moon2/values.yaml#L4) field of this chart to provide your Ingress definition via `values.yaml`. But that's more complicated than just changing Moon host name to another value.

**Comment by podguzovvasily** [comment]
Thanks @vania-pooh Resolved by creation subdomain with the same IP.
