### ISSUE TITLE
Image version for moon is hardcoded as chart version

### ISSUE THREAD

**Issue by marcinbojko** [aerokube/charts#23]
It could be nice if we could choose to override images (for example to 'latest') instead of values from chart version.
https://github.com/aerokube/charts/blob/b126080e31c44c9a61bcd0f865052ebe565c2670/moon/templates/moon.yaml#L150

**Comment by vania-pooh** [comment]
This was fixed in 32ff833e8709cfb8841a032a40cb32759d750330. Respective key is `moon.image`.
