### ISSUE TITLE
Immutable chart versioning

### ISSUE THREAD

**Issue by marcinbojko** [aerokube/charts#5]
Seems guys, you don't have chart versioning. This is a little confusing, as every deploy using tagged helm chart should be identical.
So we need: helm versioning+chart packing, or master branch versioning aligned with chart versioning.

**Comment by vania-pooh** [comment]
@marcinbojko we do https://github.com/aerokube/charts/releases/tag/1.0.0.

**Comment by marcinbojko** [comment]
Thanks @vania-pooh.
It depends on your work style, for which I am not familiar. For example:  do all commits to dev branch, then announce master.
Or do some helm repo --merge with charts presented as tgz.
Last options, triggered only on PR to master will not touch previous charts.

**Comment by vania-pooh** [comment]
@marcinbojko we prefer to merge PRs to master and just tag releases when they were fully tested. So master is unstable, but tagged master becomes stable.

**Comment by marcinbojko** [comment]
if am seeing this correctly, this means: both (tagged 1.0.0 release and latest commit) have chart in version 1.0.0 but different template content.
And with every commit (without changing chart version in file) we have differences.

**Comment by vania-pooh** [comment]
@marcinbojko we are expected to change chart version e.g. to 1.0.1 before next release.

**Comment by marcinbojko** [comment]
I understand.

**Comment by marcinbojko** [comment]
Thank you for explanation, seems i didn't pay enough attention charts aren't served from github directly anymore, and at: 
https://charts.aerokube.com/ there IS versioning established.

**Comment by vania-pooh** [comment]
@marcinbojko yeah, we have an S3 bucket where tarballs are explicitly uploaded.
