### ISSUE TITLE
Imposible to upgrade chart 1.1.14 -> 1.1.15

### ISSUE THREAD

**Issue by MrEcco** [aerokube/charts#76]
The new version of the chart contains a priorityClass definition that defaults to "default". This can block upgrade for clusters without priorityClass "default" objects (GKE have no this class by default).So, updating the chart throws a timeout error.

It would be nice to keep the value of priorityClassName `null` (unexists) if the value not present in chart values.

**Comment by MrEcco** [comment]
As I see, the problem is [fixed in code](https://github.com/aerokube/charts/commit/ce7aa84d96e4126e56f89d4bf842f6a6d4cbb0fd), but still present in the latest version in the charts repository. How often do you sync code and charts repo?

**Comment by vania-pooh** [comment]
See: https://github.com/aerokube/charts/releases/tag/1.1.16
