### ISSUE TITLE
Helm chart is not working.

### ISSUE THREAD

**Issue by Aman-singh-wq** [aerokube/charts#77]
getting "Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1" " error.  Please help

**Comment by Aman-singh-wq** [comment]
helm version - version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

**Comment by vania-pooh** [comment]
@Aman-singh-wq what is your Kubernetes version? This notation is stable since Kubernetes 1.19. https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

**Comment by Aman-singh-wq** [comment]
Client Version: v1.21.2-13+d2965f0db10712
Server Version: v1.18.20-eks-8c579e
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

Please find the version of k8

**Comment by Aman-singh-wq** [comment]
@vania-pooh can you try install moon with helm chart ?

**Comment by vania-pooh** [comment]
@Aman-singh-wq as I said `networking.k8s.io/v1` is available since Kubernetes 1.19, you have 1.18. Either update Kubernetes, or use chart version 1.13.0 and older.

**Comment by Aman-singh-wq** [comment]
Thanks @vania-pooh  it works for me.

**Comment by vania-pooh** [comment]
@Aman-singh-wq closing then.
